
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.aarch64-cpu]]
version = "10.0.0"
criteria = "safe-to-deploy"

[[exemptions.aarch64-paging]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.aarch64-rt]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.atomic]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.17.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.24"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.19"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor-macros]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor-timer-queue]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-futures]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.embassy-sync]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.embassy-time]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-time-driver]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.embassy-time-queue-utils]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-async]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-io-async]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-timer]]
version = "3.0.3"
criteria = "safe-to-run"

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.3"
criteria = "safe-to-run"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.76"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.172"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.27"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.num_enum]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.num_enum_derive]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "3.3.0"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.rstest]]
version = "0.26.1"
criteria = "safe-to-run"

[[exemptions.rstest_macros]]
version = "0.26.1"
criteria = "safe-to-run"

[[exemptions.rustversion]]
version = "1.0.21"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.subenum]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.100"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.tock-registers]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.9"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.22.26"
criteria = "safe-to-run"

[[exemptions.uuid]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.0"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.1"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.7.10"
criteria = "safe-to-run"
